server:
  port: 8765

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/workload?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
url:
  loginApi: https://sduonline.cn/isduapi/api/auth/login/system/
  sdInfApi: https://sduonline.cn/isduapi/api/edu/personal_info

checkString: xszxjcwx

expireTime: 2592000000

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.example.wordload.entities